### ISSUE TITLE
Problem adding additional users

### ISSUE THREAD

**Issue by cdipe** [wcel/moodle-mod_dialogue#39]
When starting a new dialogue and already having added one user (out of several), and are trying to add another user to open a dialogue with, there's no result in the "People" field.

I have the impression that this should be possible?

I am using Moodle 2.8.7+ and Dialogue 2.8 (2014112601), it seems to be affection newer versions as well.

Discussion:
[https://moodle.org/mod/forum/discuss.php?d=327564#p1317175]

![dialogue](https://cloud.githubusercontent.com/assets/14754240/13244246/100b1fe0-da05-11e5-9e5c-31bd00350b5e.png)

**Comment by neeesn** [comment]
I have a moodle 2.9.4 site where it doesnt work either

**Comment by Albertf27** [comment]
We have just installed Moodle 3.0.1 and the Dialogue feature of being able to have each student privately exchange comments with all of the teachers with whom he/she receives classes would be wonderful. Forums is not the right place, it's public. Chat is the wrong medium; it's for short interchanges. i.e. One-to-Many fits the bill for us and, no doubt others.

**Comment by troywilliams** [comment]
You can use the forum tool for private discussion. See https://www.it.umass.edu/support/moodle/set-up-student-journals-moodle.

**Comment by Albertf27** [comment]
Troy, many thanks for your useful and pertinent answer.

**Comment by cdipe** [comment]
Sorry, I misunderstood the "People" search field. Thought you also could bulk open dialogues with selected users.
